# Generated by Django 2.1.5 on 2019-02-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(auto_created=True)),
                ('schedule', models.CharField(max_length=250)),
                ('seat_names', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=1)),
                ('ticket', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('phone_verified', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('boarding_points', models.CharField(max_length=250)),
                ('seat_number', models.TextField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=250)),
                ('departure_date', models.DateTimeField(auto_now_add=True)),
                ('availabile_services', models.TextField(blank=True)),
                ('boarding_points', models.TextField(blank=True)),
                ('dropping_points', models.CharField(max_length=250)),
                ('fare', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_created=True)),
                ('departure_date', models.DateField(auto_created=True)),
                ('from_address', models.CharField(max_length=250)),
                ('to_address', models.CharField(max_length=250)),
                ('passengers', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=250)),
                ('selected_seat', models.IntegerField(default=0)),
                ('available_seat', models.IntegerField(default=0)),
                ('booked_seat', models.IntegerField(default=0)),
                ('fare', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeatTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='')),
                ('seat_count', models.IntegerField(default=0)),
                ('seat_name', models.TextField()),
                ('seat_price', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('journey', models.CharField(max_length=250)),
                ('bus_operator', models.CharField(max_length=250)),
                ('seat_count', models.IntegerField(default=0)),
                ('fare', models.IntegerField(default=0)),
                ('seat_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.SeatTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('fare', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.SeatTemplate')),
            ],
        ),
    ]
